name: lib-test

on: [push, pull_request]

defaults:
    run:
        shell: bash

jobs:
    build-test:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:

            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: fortran-lang/setup-fpm@v7
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}

            - run: fpm -v

            - name: Install dependencies Ubuntu
              run: |
                sudo apt-get update
                sudo apt install -y gfortran
                gfortran --version
