name: lib-test-ford

on: [push, pull_request]

defaults:
    run:
        shell: bash

jobs:
    build-test-ford:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:

            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: fortran-lang/setup-fpm@v7
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}

            - run: fpm -v

            - name: Install dependencies Ubuntu for test
              run: |
                sudo apt-get update
                sudo apt install -y gfortran
                gfortran --version

            - name: Build and Test
              run: fpm test --flag "-Wall -Wextra -ffree-line-length-none"

            - name: Install dependencies Ubuntu for documentation
              run: |
                sudo pip install ford
                ford --version

            - name: Build developer documentation
              run: ford ford.md

            - name: Upload documentation files as artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                path: doc

    deploy:
        environment:
           name: github-pages
           url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build-test-ford
        permissions:
            id-token: write
            pages: write
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
